spring:
  application:
    name: cli-template

# ログ出力
logging:

  level:
    ROOT: WARN
    jp.co.biglobe: DEBUG

  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss.SSS} [%level] [%thread] [%logger] %message%n"
